### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Cynjaman1019** [OyotOnyenwe/serversite#1]
"plugins" is misspelled as "pugins"
https://github.com/OyotOnyenwe/serversite/blob/ac7f2e06232f39c25cdcde8c58e5c4651276efaa/index.html#L118

"simplicity" is misspelled as "simplicty"
https://github.com/OyotOnyenwe/serversite/blob/ac7f2e06232f39c25cdcde8c58e5c4651276efaa/survival.html#L66

Changelog isn't up-to-date, but that's whatever

**Comment by OyotOnyenwe** [comment]
fixed in commits 349c3fa1e1dcf23bcf36d2bc2dc773533b515c17 & 2fc86e50599614f210a3f0097474bb5569c42f12

changelog will be updated at another time
